// 마이그레이션 비교 스크립트
const dbMigrations = [
  "001_create_organizations_and_memberships",
  "002_create_webinars_and_registrations",
  "003_create_interactions",
  "004_create_billing_and_audit",
  "005_create_triggers",
  "006_enable_rls_and_create_helper_views",
  "007_rls_policies_organizations",
  "008_rls_policies_webinars",
  "009_rls_policies_interactions",
  "010_rls_policies_billing_audit",
  "011_create_client_invitations",
  "fix_webinars_rls_policy",
  "fix_agency_members_rls_for_webinars",
  "fix_profiles_rls_for_webinars",
  "fix_rls_infinite_recursion",
  "simplify_profiles_rls",
  "simplify_client_members_rls",
  "fix_all_rls_circular_reference",
  "fix_registrations_rls_circular",
  "remove_circular_reference_completely",
  "fix_manage_agency_members_rls",
  "simplify_manage_agency_members_completely",
  "allow_read_profiles_in_same_webinar",
  "allow_read_profiles_for_webinar_participants",
  "enable_realtime_for_messages",
  "add_client_msg_id_to_messages",
  "add_messages_cursor_index",
  "add_answer_to_questions",
  "create_webinar_files",
  "create_giveaways",
  "create_forms_system",
  "add_opened_closed_at_to_forms",
  "fix_fill_org_fields_for_forms",
  "fix_fill_org_fields_for_forms_v2",
  "fix_fill_org_fields_record_assignment",
  "add_org_fields_to_form_tables",
  "fix_fill_org_fields_remove_record_w",
  "optimize_form_loading_indexes",
  "create_me_view",
  "setup_profiles_rls",
  "fix_profiles_rls_recursion",
  "fix_profiles_rls_recursion_v2",
  "fix_profiles_rls_simple_v2",
  "fix_profiles_rls_bypass",
  "fix_profiles_rls_final",
  "remove_superadmin_rls_policy",
  "simplify_messages_rls",
  "add_nickname_to_registrations",
  "add_nickname_to_profiles",
  "create_short_links",
  "add_client_id_to_invitations",
  "add_member_role_to_client_members",
  "create_webinar_allowed_emails",
  "create_webinar_stats_v2",
  "create_event_survey_campaigns",
  "modify_forms_for_campaigns",
  "make_form_submissions_nullable_for_public_surveys",
  "add_consent_data_to_survey_entries",
  "add_form_config_column",
  "add_dashboard_code_to_campaigns",
  "create_survey_analysis_reports",
  "add_is_public_to_analysis_reports",
  "extend_survey_analysis_reports_v2",
  "add_analysis_decision_pack_to_reports",
  "add_type_to_event_campaigns",
  "add_registration_fields_to_entries",
  "add_analysis_role_override_to_form_questions",
  "extend_role_override_check_constraint",
  "create_survey_analysis_guidelines",
  "add_form_revision",
  "create_registry_tables",
  "seed_registry_data",
  "add_guideline_pack_compiled",
  "create_uslab_images_bucket",
  "add_registration_campaign_to_webinars",
  "add_email_template_to_webinars",
  "add_name_email_auth_policy",
  "add_webinar_start_time",
  "add_role_and_registered_via_to_registrations",
  "fix_registrations_role_constraint",
  "update_registration_data_fields",
  "add_utm_tracking_to_entries",
  "create_marketing_summary_rpc",
  "create_campaign_link_meta",
  "add_start_date_to_campaign_link_meta",
  "add_cid_to_campaign_link_meta",
  "add_meta_fields_to_webinars",
  "add_meta_thumbnail_to_webinars",
  "add_meta_fields_to_campaigns",
  "create_event_access_logs",
  "create_visits_cvr_rpc",
  "072_add_manual_registrations_to_entries",
  "073_add_registration_data_to_registrations",
  "074_add_webinar_id_to_access_logs",
  "075_add_survey_no_to_registrations",
  "076_add_dashboard_code_to_webinars",
  "create_notes_tables",
  "add_type_to_webinars",
  "add_settings_to_webinars",
  "create_email_campaigns",
  "enable_registration_campaign_email",
  "add_email_campaign_header_footer"
];

const localFiles = [
  "011_create_client_invitations",
  "012_add_client_msg_id_to_messages",
  "013_add_messages_cursor_index",
  "014_add_answer_to_questions",
  "015_create_forms_system",
  "016_create_webinar_files",
  "017_create_giveaways",
  "018_add_opened_closed_at_to_forms",
  "019_fix_fill_org_fields_for_forms",
  "020_add_org_fields_to_form_tables",
  "021_optimize_form_loading_indexes",
  "022_create_me_view",
  "023_setup_profiles_rls",
  "024_fix_profiles_rls_recursion",
  "025_simplify_messages_rls",
  "026_create_short_links",
  "027_add_nickname_to_registrations",
  "028_add_nickname_to_profiles",
  "029_add_client_id_to_invitations",
  "030_add_member_role_to_client_members",
  "031_create_webinar_allowed_emails",
  "032_add_slug_to_webinars",
  "033_create_webinar_stats_v2",
  "034_create_event_survey_campaigns",
  "035_modify_forms_for_campaigns",
  "036_make_form_submissions_nullable_for_public_surveys",
  "037_add_consent_data_to_survey_entries",
  "038_add_form_config_for_survey_fields",
  "039_add_dashboard_code_to_campaigns",
  "040_create_survey_analysis_reports",
  "041_add_is_public_to_analysis_reports",
  "042_extend_survey_analysis_reports_v2",
  "043_add_analysis_decision_pack_to_reports",
  "044_add_type_to_event_campaigns",
  "045_add_registration_fields_to_entries",
  "046_add_unsubscribe_system",
  "047_add_analysis_role_override_to_form_questions",
  "048_extend_role_override_check_constraint",
  "049_create_survey_analysis_guidelines",
  "050_add_logical_key_to_form_questions",
  "051_add_form_revision",
  "052_create_registry_tables",
  "053_seed_registry_data",
  "054_add_email_template_to_webinars",
  "055_add_registration_campaign_to_webinars",
  "056_add_name_email_auth_policy",
  "057_add_webinar_start_time",
  "058_add_role_and_registered_via_to_registrations",
  "059_fix_registrations_role_constraint",
  "060_add_project_name_to_webinars",
  "061_add_message_to_registration_data",
  "062_update_registration_data_fields",
  "063_add_utm_tracking_to_entries",
  "064_create_marketing_summary_rpc",
  "065_create_campaign_link_meta",
  "066_add_start_date_to_campaign_link_meta",
  "067_add_cid_to_campaign_link_meta",
  "068_add_meta_fields_to_webinars",
  "069_add_meta_thumbnail_to_webinars",
  "070_add_meta_fields_to_campaigns",
  "071_create_event_access_logs",
  "072_add_manual_registrations_to_entries",
  "072_add_webinar_support_to_campaign_link_meta",
  "073_add_registration_data_to_registrations",
  "074_add_webinar_id_to_access_logs",
  "075_add_survey_no_to_registrations",
  "076_add_dashboard_code_to_webinars",
  "077_add_marketing_campaign_link_id_to_registrations",
  "078_add_cid_to_event_access_logs",
  "078_fix_marketing_summary_rpc",
  "079_create_marketing_stats_daily",
  "080_fix_cvr_precision",
  "081_add_type_to_webinars",
  "082_add_settings_to_webinars",
  "083_create_email_campaigns",
  "084_enable_registration_campaign_email",
  "085_add_email_campaign_header_footer",
  "20260128_create_notes_tables"
];

// 이름에서 숫자 접두사 제거
const normalizeName = (name: string) => {
  return name.replace(/^\d+_/, '').replace(/\.sql$/, '');
};

const dbNormalized = dbMigrations.map(normalizeName);
const localNormalized = localFiles.map(normalizeName);

console.log('=== 데이터베이스에만 있는 마이그레이션 ===');
const onlyInDb = dbNormalized.filter(name => !localNormalized.includes(name));
onlyInDb.forEach(name => console.log(`  - ${name}`));

console.log('\n=== 로컬에만 있는 마이그레이션 ===');
const onlyInLocal = localNormalized.filter(name => !dbNormalized.includes(name));
onlyInLocal.forEach(name => console.log(`  - ${name}`));

console.log(`\n총 데이터베이스 마이그레이션: ${dbMigrations.length}`);
console.log(`총 로컬 마이그레이션 파일: ${localFiles.length}`);
console.log(`데이터베이스에만 있음: ${onlyInDb.length}`);
console.log(`로컬에만 있음: ${onlyInLocal.length}`);
